spring.application.name=Servicio-aulas

# ===== Server (Railway inyecta PORT, local usa 8082) =====
server.port=${PORT:8082}

# ===== Datasource MySQL =====
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ServicioAulas?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:bas1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / Hibernate =====
# En producción real lo ideal es 'validate' + Flyway. Para academia 'update' está bien.
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===== Jackson =====
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Lima

# ===== JWT =====
jwt.secret=${JWT_SECRET:4e6d2fdfef74954c3b3e58914ff47bb13714ed11454e7bc2aa50f60ea1737695a858a297871c8c5eb55e849e4f19473838133e8715704251db5d30bec3fd8a31}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

# ===== Logging (sube nivel en local, baja en prod) =====
logging.level.org.springframework.security=${LOG_LEVEL_SECURITY:INFO}
logging.level.com.aulas=${LOG_LEVEL_APP:INFO}